Сделал случайно генерирующиеся пины, дз попытка №1
htmlacademy-javascript/88443-keksobooking-21 pull request #2
Opened 2020-10-10 18:24 UTC by Castoco

2020-10-11 09:11 UTC, 4err requested changes
https://take.ms/XuOA5 Изображения не должны повторяться.

2020-10-11 09:11 UTC, 4err commented on js/main.js
> +const PIN_HEIGHT = -70;
Высота не может быть отрицательной. Лучше тогда использовтаь другой термин, например - отступ или смещение.

2020-10-11 09:11 UTC, 4err commented on js/main.js
> +  const pinLocationX = getRandomNumber(0, 900);
Магические числа здесь и далее. Все не вычисляемые числа нужно вынести в константы.

2020-10-11 09:11 UTC, 4err commented on js/main.js
> +  }
А для чего тут цикл?

2020-10-11 22:56 UTC, Castoco commented on js/main.js
> +  const pinLocationX = getRandomNumber(0, 900);
а по поводу 0, ну ноль он же и есть ноль, в функции он задает начало, его тоже в конснанту?

2020-10-13 05:17 UTC, 4err requested changes

2020-10-13 05:17 UTC, 4err commented on js/main.js
> +const MAP_BOTTOM_Y = 620;
https://up.htmlacademy.ru/javascript/21/project/keksobooking#keksobooking-4-4

Почему 620 если 630?

2020-10-13 05:17 UTC, 4err commented on js/main.js
> +const MAP_WIDTH = 900;
Почему 900, если ширина 1200?

2020-10-13 05:17 UTC, 4err commented on js/main.js
> +const getStrLength = function (arr) {
Исходя из названия функции она должна возвращать длинну строки. Хотя это не так. Лучше переименовать во что-то более точно описывающее ее действие.

2020-10-13 05:17 UTC, 4err commented on js/main.js
> +        'address': `Адрес предложения ${pinLocationX}, ${pinLocationY}`,
Технически это ошибка ТЗ, т.к. тут должная быть строка только с координатами, но пусть.

2020-10-13 05:17 UTC, 4err commented on js/main.js
> +  let element = pinTemplate.cloneNode(true);
const же

2020-10-13 11:54 UTC, 4err requested changes

2020-10-13 11:54 UTC, 4err commented on js/main.js
> +  element.style = `left: ${render.location.x}px; top: ${render.location.y + PIN_SCALE}px;`;
Так а ширину то учитывать нужно, сейчас у тебя кончик показывает не на координату.

2020-10-13 12:31 UTC, merged